pkgname="models"
output="models"
schema="public"
[psql]
    dbname = "patientdb"
    user = "docker"
    pass = "docker"
    host = "localhost"
    sslmode = "disable"

[aliases.tables.patient_note.columns]
patientid = "Patient_Id"
userid = "User_Id"
