// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Patient is an object representing the database table.
type Patient struct {
	Patientid string    `boil:"patientid" json:"patientid" toml:"patientid" yaml:"patientid"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Location  string    `boil:"location" json:"location" toml:"location" yaml:"location"`
	Created   null.Time `boil:"created" json:"created,omitempty" toml:"created" yaml:"created,omitempty"`

	R *patientR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L patientL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PatientColumns = struct {
	Patientid string
	Name      string
	Location  string
	Created   string
}{
	Patientid: "patientid",
	Name:      "name",
	Location:  "location",
	Created:   "created",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var PatientWhere = struct {
	Patientid whereHelperstring
	Name      whereHelperstring
	Location  whereHelperstring
	Created   whereHelpernull_Time
}{
	Patientid: whereHelperstring{field: "\"patient\".\"patientid\""},
	Name:      whereHelperstring{field: "\"patient\".\"name\""},
	Location:  whereHelperstring{field: "\"patient\".\"location\""},
	Created:   whereHelpernull_Time{field: "\"patient\".\"created\""},
}

// PatientRels is where relationship names are stored.
var PatientRels = struct {
	PatientidPatientNotes string
}{
	PatientidPatientNotes: "PatientidPatientNotes",
}

// patientR is where relationships are stored.
type patientR struct {
	PatientidPatientNotes PatientNoteSlice
}

// NewStruct creates a new relationship struct
func (*patientR) NewStruct() *patientR {
	return &patientR{}
}

// patientL is where Load methods for each relationship are stored.
type patientL struct{}

var (
	patientAllColumns            = []string{"patientid", "name", "location", "created"}
	patientColumnsWithoutDefault = []string{"patientid", "name", "location"}
	patientColumnsWithDefault    = []string{"created"}
	patientPrimaryKeyColumns     = []string{"patientid"}
)

type (
	// PatientSlice is an alias for a slice of pointers to Patient.
	// This should generally be used opposed to []Patient.
	PatientSlice []*Patient
	// PatientHook is the signature for custom Patient hook methods
	PatientHook func(context.Context, boil.ContextExecutor, *Patient) error

	patientQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	patientType                 = reflect.TypeOf(&Patient{})
	patientMapping              = queries.MakeStructMapping(patientType)
	patientPrimaryKeyMapping, _ = queries.BindMapping(patientType, patientMapping, patientPrimaryKeyColumns)
	patientInsertCacheMut       sync.RWMutex
	patientInsertCache          = make(map[string]insertCache)
	patientUpdateCacheMut       sync.RWMutex
	patientUpdateCache          = make(map[string]updateCache)
	patientUpsertCacheMut       sync.RWMutex
	patientUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var patientBeforeInsertHooks []PatientHook
var patientBeforeUpdateHooks []PatientHook
var patientBeforeDeleteHooks []PatientHook
var patientBeforeUpsertHooks []PatientHook

var patientAfterInsertHooks []PatientHook
var patientAfterSelectHooks []PatientHook
var patientAfterUpdateHooks []PatientHook
var patientAfterDeleteHooks []PatientHook
var patientAfterUpsertHooks []PatientHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Patient) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Patient) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Patient) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Patient) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Patient) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Patient) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Patient) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Patient) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Patient) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range patientAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPatientHook registers your hook function for all future operations.
func AddPatientHook(hookPoint boil.HookPoint, patientHook PatientHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		patientBeforeInsertHooks = append(patientBeforeInsertHooks, patientHook)
	case boil.BeforeUpdateHook:
		patientBeforeUpdateHooks = append(patientBeforeUpdateHooks, patientHook)
	case boil.BeforeDeleteHook:
		patientBeforeDeleteHooks = append(patientBeforeDeleteHooks, patientHook)
	case boil.BeforeUpsertHook:
		patientBeforeUpsertHooks = append(patientBeforeUpsertHooks, patientHook)
	case boil.AfterInsertHook:
		patientAfterInsertHooks = append(patientAfterInsertHooks, patientHook)
	case boil.AfterSelectHook:
		patientAfterSelectHooks = append(patientAfterSelectHooks, patientHook)
	case boil.AfterUpdateHook:
		patientAfterUpdateHooks = append(patientAfterUpdateHooks, patientHook)
	case boil.AfterDeleteHook:
		patientAfterDeleteHooks = append(patientAfterDeleteHooks, patientHook)
	case boil.AfterUpsertHook:
		patientAfterUpsertHooks = append(patientAfterUpsertHooks, patientHook)
	}
}

// One returns a single patient record from the query.
func (q patientQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Patient, error) {
	o := &Patient{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for patient")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Patient records from the query.
func (q patientQuery) All(ctx context.Context, exec boil.ContextExecutor) (PatientSlice, error) {
	var o []*Patient

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Patient slice")
	}

	if len(patientAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Patient records in the query.
func (q patientQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count patient rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q patientQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if patient exists")
	}

	return count > 0, nil
}

// PatientidPatientNotes retrieves all the patient_note's PatientNotes with an executor via patientid column.
func (o *Patient) PatientidPatientNotes(mods ...qm.QueryMod) patientNoteQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"patient_note\".\"patientid\"=?", o.Patientid),
	)

	query := PatientNotes(queryMods...)
	queries.SetFrom(query.Query, "\"patient_note\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"patient_note\".*"})
	}

	return query
}

// LoadPatientidPatientNotes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (patientL) LoadPatientidPatientNotes(ctx context.Context, e boil.ContextExecutor, singular bool, maybePatient interface{}, mods queries.Applicator) error {
	var slice []*Patient
	var object *Patient

	if singular {
		object = maybePatient.(*Patient)
	} else {
		slice = *maybePatient.(*[]*Patient)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &patientR{}
		}
		args = append(args, object.Patientid)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &patientR{}
			}

			for _, a := range args {
				if a == obj.Patientid {
					continue Outer
				}
			}

			args = append(args, obj.Patientid)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`patient_note`), qm.WhereIn(`patient_note.patientid in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load patient_note")
	}

	var resultSlice []*PatientNote
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice patient_note")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on patient_note")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for patient_note")
	}

	if len(patientNoteAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PatientidPatientNotes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &patientNoteR{}
			}
			foreign.R.Patientid = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Patientid == foreign.Patient_Id {
				local.R.PatientidPatientNotes = append(local.R.PatientidPatientNotes, foreign)
				if foreign.R == nil {
					foreign.R = &patientNoteR{}
				}
				foreign.R.Patientid = local
				break
			}
		}
	}

	return nil
}

// AddPatientidPatientNotes adds the given related objects to the existing relationships
// of the patient, optionally inserting them as new records.
// Appends related to o.R.PatientidPatientNotes.
// Sets related.R.Patientid appropriately.
func (o *Patient) AddPatientidPatientNotes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PatientNote) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Patient_Id = o.Patientid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"patient_note\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"patientid"}),
				strmangle.WhereClause("\"", "\"", 2, patientNotePrimaryKeyColumns),
			)
			values := []interface{}{o.Patientid, rel.Noteid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Patient_Id = o.Patientid
		}
	}

	if o.R == nil {
		o.R = &patientR{
			PatientidPatientNotes: related,
		}
	} else {
		o.R.PatientidPatientNotes = append(o.R.PatientidPatientNotes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &patientNoteR{
				Patientid: o,
			}
		} else {
			rel.R.Patientid = o
		}
	}
	return nil
}

// Patients retrieves all the records using an executor.
func Patients(mods ...qm.QueryMod) patientQuery {
	mods = append(mods, qm.From("\"patient\""))
	return patientQuery{NewQuery(mods...)}
}

// FindPatient retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPatient(ctx context.Context, exec boil.ContextExecutor, patientid string, selectCols ...string) (*Patient, error) {
	patientObj := &Patient{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"patient\" where \"patientid\"=$1", sel,
	)

	q := queries.Raw(query, patientid)

	err := q.Bind(ctx, exec, patientObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from patient")
	}

	return patientObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Patient) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no patient provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(patientColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	patientInsertCacheMut.RLock()
	cache, cached := patientInsertCache[key]
	patientInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			patientAllColumns,
			patientColumnsWithDefault,
			patientColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(patientType, patientMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"patient\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"patient\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into patient")
	}

	if !cached {
		patientInsertCacheMut.Lock()
		patientInsertCache[key] = cache
		patientInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Patient.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Patient) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	patientUpdateCacheMut.RLock()
	cache, cached := patientUpdateCache[key]
	patientUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			patientAllColumns,
			patientPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update patient, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"patient\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, patientPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, append(wl, patientPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update patient row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for patient")
	}

	if !cached {
		patientUpdateCacheMut.Lock()
		patientUpdateCache[key] = cache
		patientUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q patientQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for patient")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for patient")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PatientSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"patient\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, patientPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in patient slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all patient")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Patient) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no patient provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(patientColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	patientUpsertCacheMut.RLock()
	cache, cached := patientUpsertCache[key]
	patientUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			patientAllColumns,
			patientColumnsWithDefault,
			patientColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			patientAllColumns,
			patientPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert patient, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(patientPrimaryKeyColumns))
			copy(conflict, patientPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"patient\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(patientType, patientMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(patientType, patientMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert patient")
	}

	if !cached {
		patientUpsertCacheMut.Lock()
		patientUpsertCache[key] = cache
		patientUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Patient record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Patient) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Patient provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), patientPrimaryKeyMapping)
	sql := "DELETE FROM \"patient\" WHERE \"patientid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from patient")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for patient")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q patientQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no patientQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from patient")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for patient")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PatientSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(patientBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"patient\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, patientPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from patient slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for patient")
	}

	if len(patientAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Patient) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPatient(ctx, exec, o.Patientid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PatientSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PatientSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), patientPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"patient\".* FROM \"patient\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, patientPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PatientSlice")
	}

	*o = slice

	return nil
}

// PatientExists checks if the Patient row exists.
func PatientExists(ctx context.Context, exec boil.ContextExecutor, patientid string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"patient\" where \"patientid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, patientid)
	}
	row := exec.QueryRowContext(ctx, sql, patientid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if patient exists")
	}

	return exists, nil
}
