// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Patients", testPatientsUpsert)

	t.Run("PatientNotes", testPatientNotesUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
